custom_components/mail_and_packages/sensor.py
Seems like a silly change but I don't believe the unit of measurement is required, and if you display the sensor as an entity in lovelace, by default it will say "Feb-12-2020 02:23 PM Time".  Removing the lines will make it read more correctly as just "Feb-12-2020 02:23 PM"
=> Remove unit of time measurement

.gitignore, custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/manifest.json, custom_components/mail_and_packages/sensor.py, hacs.json
* Only login to email once and pull all the emails needed in one swoop - Fixes #14 
* Changed GIF rotation time to 5 seconds - Fixes #33 
* Subtract delivered packages from 'in transit' packages, should no longer result in negative counts - Fixes #5 and Fixes #36 
* No more slow start warnings since we check the email in one call now - Fixes #10 
* Added aspect ratio calculations to keep image looking correctly - Fixes #32 
* Added additional subject searches for FedEx emails - Fixes #34 
* Bump version to 0.1.0 since we're no longer using Imagemagick and fixed the speed issues, seemed like a good milestone.
=> Efficiency patch

custom_components/mail_and_packages/sensor.py
1. Removed the code to check for and copy mail_none.gif and image-no-mailpieces700.jpg to the image path. 
2. Changed code to add the image-no-mailpieces700.jpg to the array from the custom_component folder
3. Changed code to create the no mail gif to copy mail_none.gif from the custom component folder
4. Updated the ImagesDelete to be a copy of the image list at that point in time instead of a reference to the images array
=> Image no mailpieces700 fix

custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/sensor.py
The update() method of the sensor iterates through sensors in the order they appear in the \_resources list. Some sensors, such as the \*\_delivering and zpackages\_\* sensors, depend on the values of earlier sensors to compute their value. If the _resources list is not in exactly the right order, this causes these sensors to show the wrong value. Performing setup through the UI does not sort this list, and can cause the summary sensors (zpackages\_\*) to break.
To fix this issue, abstract the "fetch one sensor" logic into a fetch() method. That method can recursively call itself to fetch the value of any of its dependencies. The values are cached, so that a given sensor will only be computed once per update() pass, regardless of how many times that sensor is fetch()ed.
=> Fix order sensitivity of sensor computation.

custom_components/mail_and_packages/helpers.py
Change message from warn to debug level for Amazon emails that don't decode properly.
- This PR is related to issue: https://community.home-assistant.io/t/mail-and-packages-custom-component-for-ups-fedex-and-usps/118081/1254
=> Change message from warn to debug level

custom_components/mail_and_packages/config_flow.py, custom_components/mail_and_packages/strings.json, custom_components/mail_and_packages/translations/en.json, tests/test_config_flow.py
A better fix for config flow defaults.
Added an additional test for config flow with missing/incomplete data.
Update config flow text to specify the minimum values for "imap timeout" and "scan interval".
- This PR fixes or closes issue: fixes #375
=> Better fix for config flow defaults

custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/helpers.py, custom_components/mail_and_packages/sensor.py
Entities are now using `Entity Description`s, this means you will need version 2021.11.x+
Utilize entity descriptions where applicable.
=> refactor: utilize EntityDescription

custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/helpers.py
Fix NoneType error when Amazon Hub is in use
- This PR fixes or closes issue: fixes #568
=> fix: Guard against NoneType value when using group in Amazon hub parsing

custom_components/mail_and_packages/camera.py, custom_components/mail_and_packages/sensor.py
Due to core changes this will be incompatible with older version of Home Assistant.
Changes for Home Assistant 2021.21.0+, changes `device_state_attributes` to `extra_state_attributes`
=> fix: change to extra_state_attributes

custom_components/mail_and_packages/__init__.py, custom_components/mail_and_packages/config_flow.py, custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/helpers.py, custom_components/mail_and_packages/sensor.py, custom_components/mail_and_packages/strings.json, custom_components/mail_and_packages/translations/en.json, tests/const.py, tests/test_config_flow.py, tests/test_sensor.py
Allow the `days` back email lookup for the amazon sensor to be configurable.
- This PR is related to issue: https://community.home-assistant.io/t/mail-and-packages-custom-component-for-ups-fedex-and-usps/118081/1625
=> feat: make amazon sensor more configurable

custom_components/mail_and_packages/helpers.py, tests/conftest.py, tests/test_emails/amazon_fwd.eml, tests/test_helpers.py
Strip `>` from forwarded Amazon emails
- This PR is related to issue: https://community.home-assistant.io/t/mail-and-packages-custom-component-for-ups-fedex-and-usps/118081/1658
=> fix: strip `>` from forwarded amazon date capture

.github/workflows/pytest.yaml, custom_components/mail_and_packages/const.py, tests/test_helpers.py
Added amazon.com.au domain and updated subject for auspost_delivering as the subject in the emails either say "Your delivery from XXX is on its way" or "Your delivery from XXX is coming today"
Added `amazon.com.au` domain and updated subject for `auspost_delivering` similar to `royal_delivering` to account for the different email subjects
=> fix(shipper): add amazon.com.au and update auspost_delivering

custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/helpers.py, custom_components/mail_and_packages/sensor.py, tests/test_helpers.py, tests/test_sensor.py
Make the `mail_updated` sensor properly use datetime object for HA core 2022.4
=> fix: changes for HA core 2022.4

README.md
I updated the HACS Badge URL to the new hacs/integration.
=> docs: Update HACS URL

custom_components/mail_and_packages/binary_sensor.py, tests/const.py, tests/test_binary_sensor.py
Fix binary sensors not updating due to wrong path being checked.
Add more debugging statements.
=> fix: binary sensors not updating

custom_components/mail_and_packages/binary_sensor.py
Fix wrong filename specified for the amazon image binary sensor.
=> fix: wrong filename for amazon binary_sensor

custom_components/mail_and_packages/const.py
Add the amazon.es confirmation email to the search from newly added domain
- This PR fixes or closes issue: fixes #698
=> fix: add amazon confirmation email address for amazon.es

custom_components/mail_and_packages/helpers.py, tests/conftest.py
Pad images so they are all the same size when resized.
=> fix: add padding around images for sizing

custom_components/mail_and_packages/helpers.py
=> fix: filter out junk mail images

custom_components/mail_and_packages/const.py
Adds DHL Parcel NL tracking
This PR adds DHL Parcel NL to the plugin
=> feat(shipper): Add DHL Parcel NL

custom_components/mail_and_packages/const.py
Fixed German DHL sensor
none
German DHL sensor did not work. I adjusted the patterns so hopefully it will now detect mails correctly.
=> fix(shipper): update DHL for Germany

custom_components/mail_and_packages/sensor.py
Add key checks to sensor attributes to avoid missing keys errors.
- This PR fixes or closes issue: fixes #780
=> fix: add key checks to amazon sensors fixes #780

custom_components/mail_and_packages/helpers.py
Make sure the folder selected by user is in read only mode.
- This PR fixes or closes issue: fixes #781
=> fix: make sure the selected IMAP folder is only readonly mode

custom_components/mail_and_packages/manifest.json
Update `manifest.json` to include `integration_type` per the [Home Assistant dev docs](https://developers.home-assistant.io/docs/creating_integration_manifest).
=> chore: update integration manifest to add integration_type

custom_components/mail_and_packages/const.py, tests/test_helpers.py
Add Amazon.ae to amazon sensor.
I think we just need to add the domain, the rest of it is identical to the parent .com domain.
=> feat: add amazon.ae to amazon sensor 

custom_components/mail_and_packages/helpers.py, tests/test_helpers.py
Add flag `-pix_fmt yuv420p` to ffmpeg to create mp4 file.
- This PR fixes or closes issue: fixes #830
=> fix: add ffmpeg flag for mp4 video creation

custom_components/mail_and_packages/const.py
My building uses BuildingLink to manage the mail room... packages aren't really "delivered" until they've been processed and appear, so adding this means i can look for how many other shippers delivered vs. the number in buildinglink.
=> feat(shipper): add support for BuildingLink

custom_components/mail_and_packages/const.py
Added Walmart Delivering Sensor
Updated Walmart Delivered Sensor subject array.
Updated Walmart Delivered tracking pattern.
=> fix(shipper): added Walmart delivering sensor. Added new subject to Walmart delivered.

custom_components/mail_and_packages/const.py
Update subject for Walmart delivered sensor. Currently Subject is  "Delivered: items from order", but needs to be changes to  "Delivered:", as Walmart doesn't always use the " items from order" line in the subject.  For example, today I received an email with the subject:  "Delivered: Milk, Cheese, Pepper, Etc." and it didn't get picked up. Changing the subject query to just "Delivered:" will resolve this without breaking the query, which is what I should have done the first time.
=> fix(shipper): Updated subject for Walmart delivered sensor.

custom_components/mail_and_packages/const.py, tests/test_binary_sensor.py
Adjust device_class and enabled by default status for USPS Mail Delivered sensor
=> fix: usps_mail_delivered device_class

custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/helpers.py, tests/test_helpers.py
Allow more amazon delivered email from addresses.
- This PR is related to issue: #925
=> fix: support different from addresses on amazon delivered emails

custom_components/mail_and_packages/const.py, tests/test_helpers.py
Basically redone https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/pull/842 for the correct branch
- Add french strings to amazon + canadian french AMAZON_LANG
- Add french string to ups
- IntelCom section with french contents
=> feat(shipper): update intelcom, ups and amazon with canadian french strings

custom_components/mail_and_packages/binary_sensor.py, custom_components/mail_and_packages/sensor.py, tests/conftest.py, tests/const.py, tests/test_binary_sensor.py, tests/test_emails/usps_mail_delivered.eml
Fix small bug when enabling usps mail delivered sensor and add test email
- This PR is related to issue: #915
=> fix: fix small bug when enabling usps mail delivered sensor

custom_components/mail_and_packages/config_flow.py, tests/test_config_flow.py
Use less validation on amazon forwarding email entries.
=> refactor: less amazon forwarding email validation
