custom_components/mail_and_packages/camera.py, custom_components/mail_and_packages/sensor.py
* Added a camera component for easier inclusion into the UI
* Added "in-transit" and "delivered" sensors
=> Adds Camera and In-transit/delivered sensors

README.md
Added instructions for HACS/manual process (changed since adding HACS), removed reference to Lovelace custom card and provided alternative options.  Also provided automation and camera examples.
=> Update Readme to improve install intructions

README.md
Please check the Lovelace configuration for the custom card. I think a release can be made after that.
=> Updated config options

custom_components/mail_and_packages/.translations/en.json, custom_components/mail_and_packages/__init__.py, custom_components/mail_and_packages/config_flow.py, custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/manifest.json, custom_components/mail_and_packages/sensor.py
* Removed image resizing (for now)
* Added GIF image rotation as a configurable option this will require removal and re-adding of the integration to configure. (Default 5 seconds)
* Sensors now populate entities correctly in the integration menu and entities registry
* Some formatting fixes
* Fixes #39
=> SciPi revert

custom_components/mail_and_packages/.translations/en.json, custom_components/mail_and_packages/__init__.py, custom_components/mail_and_packages/config_flow.py, custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/manifest.json, custom_components/mail_and_packages/sensor.py
* Removed image resizing (for now)
* Added GIF image rotation as a configurable option this will require removal and re-adding of the integration to configure. (Default 5 seconds)
* Sensors now populate entities correctly in the integration menu and entities registry
* Some formatting fixes
* Fixes #39
=> SciPy revert

.github/ISSUE_TEMPLATE/bug_report.md, custom_components/mail_and_packages/.translations/en.json, custom_components/mail_and_packages/__init__.py, custom_components/mail_and_packages/config_flow.py, custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/sensor.py
None
This PR brings the ability to re-configure the integration without having to remove and re-add it.
Also added additional error catching.
None
- This PR fixes or closes issue: fixes #50 #53 
- This PR is related to issue: #50 #53
=> Add reconfiguration

custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/sensor.py
None
Adds Amazon package sensor with order number and item list attributes (if applicable)
Added Amazon package sensor with order number and item list as attributes (if applicable).
Minor formatting fixes
- This PR is related to issue: #58
=> Add Amazon Package sensor

custom_components/mail_and_packages/sensor.py
None
* Really fix negative transit count this time
None
=> Truely fix negative transit count

custom_components/mail_and_packages/config_flow.py, custom_components/mail_and_packages/const.py
None
Fix reconfig not working
None
=> Fix reconfiguration not working

custom_components/mail_and_packages/.translations/en.json, custom_components/mail_and_packages/config_flow.py, custom_components/mail_and_packages/const.py
None
* Add folder list drop down to select where your emails are located
* Version bump
* Add text for the new 2 step setup process
* Setup / Reconfigure is now a 2 step process, in step 2 the list of available folders auto populates from the mail server
n/a
- This PR is related to issue: #64
=> Add mailbox folder list to setup

custom_components/mail_and_packages/.translations/en.json
Nope
Noticed this when I was readding the integration to change image path
=> Fix en.json to reflect new image path

README.md, test.py
None
Found a few other references to www and also adding @rpietra 's updated sensor (which is much better) from https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/issues/60
- This PR fixes or closes issue: fixes #60 
- This PR is related to issue: #70 #71
=> Fix up other references to www and update sensor template

custom_components/mail_and_packages/config_flow.py, custom_components/mail_and_packages/const.py
None
* Fixed error on reconfiguration screen.
None
- This PR is related to issue: #53
=> Fix error on reconfig

custom_components/mail_and_packages/__init__.py, custom_components/mail_and_packages/config_flow.py, custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/sensor.py
None
* Fixed unloading of sensor entities
* Formatting fixes
* Version bump to -b8
* Moved directory check/creation to create the path before manipulating images
None
- This PR is related to issue: #53
=> Properly unload sensor entities

custom_components/mail_and_packages/config_flow.py, custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/sensor.py
None
Change IMAP command when searching for email
None
- This PR fixes or closes issue: fixes #64 
- This PR is related to issue: #64
=> IMAP command update

custom_components/mail_and_packages/config_flow.py, custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/sensor.py
* Security update to randomly generate the image file name
* File name is a sensor attribute that can be used for automations or scripts
* Remove single setup restriction so you can add multiple email accounts
* Added 'server' attribute to each sensor so you can tell what email server it's for
* Fix for #64 
- This PR fixes or closes issue: fixes #64 
- This PR is related to issue: #70
=> Multiple Email Accounts and Security Changes

custom_components/mail_and_packages/.translations/en.json, custom_components/mail_and_packages/config_flow.py, custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/sensor.py
This will cause the sensors not to load until you reconfigure the integration.
* Add toggle to turn on/off (On by default) the random image file names
- This PR is related to issue: #70
=> Add option to toggle image filename randomness

custom_components/mail_and_packages/config_flow.py
n/a
* Sanitize user image_path input
- This PR fixes or closes issue: fixes #88 
- This PR is related to issue: #88
=> Sanitize user image_path input

custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/sensor.py
n/a
* Fix math error on transit count
In case somehow the transit count becomes negative, we'll default it to 0. Should never happen.
- This PR fixes or closes issue: fixes #93
=> Fix math error on transit count

custom_components/mail_and_packages/config_flow.py, custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/sensor.py
n/a
Change the way sensors are generated to a single class making it easier to create/remove sensors as needed without having to create additional classes.
- This PR is related to issue: #80
=> Condense sensor

custom_components/mail_and_packages/sensor.py
n/a
* Fix image_name missing from get_mails call
n/a
=> Fix missing image_name missing

custom_components/mail_and_packages/.translations/en.json, custom_components/mail_and_packages/config_flow.py, custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/sensor.py
No breaking change
Correcting bug doubling values for carriers with no subject 2
- [ x] Bugfix (non-breaking change which fixes an issue)
- This PR is related to issue: #97
=> Fix subject 2 count indentation

README.md
This pull request only updates the README file with some spelling and grammar fixes.  No code changes.
=> Correct spelling and grammar in README

custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/sensor.py
n/a
Revise the Amazon email checker to handle emails better.
- This PR fixes or closes issue: fixes #118 fixes #106
=> Another Amazon Fix

custom_components/mail_and_packages/config_flow.py, custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/sensor.py, custom_components/mail_and_packages/translations/en.json
n/a
* Sanitize user input to disallow component directory to store the images
* Add try/except for Amazon email payload errors
* Version bump
- This PR fixes or closes issue: fixes #118 fixes #106 fixes #120
=> Disallow user from setting component directory as image path

custom_components/mail_and_packages/sensor.py
n/a
* USPS 'out for delivery' fix.
- This PR fixes or closes issue: fixes #117 fixes #92
=> Out for Delivery fix

custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/sensor.py
n/a
Formatting clean up for release
n/a
=> 0.2.0 - Release

README.md, custom_components/mail_and_packages/config_flow.py, custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/translations/en.json, info.md
None
Updated documentation, better transparency, better instruction.
Reordered configuration options in step two placing all email options and image options together
Replaced step two description with markdown and links to GitHub for more information
=> Updated Documentation and Configuration Order

custom_components/mail_and_packages/strings.json, custom_components/mail_and_packages/translations/ca.json, custom_components/mail_and_packages/translations/de.json, custom_components/mail_and_packages/translations/en.json, custom_components/mail_and_packages/translations/es.json, custom_components/mail_and_packages/translations/es_419.json, custom_components/mail_and_packages/translations/fi.json, custom_components/mail_and_packages/translations/fr.json, custom_components/mail_and_packages/translations/hu.json, custom_components/mail_and_packages/translations/it.json, custom_components/mail_and_packages/translations/ko.json, custom_components/mail_and_packages/translations/nl.json, custom_components/mail_and_packages/translations/no.json, custom_components/mail_and_packages/translations/pl.json, custom_components/mail_and_packages/translations/pt.json, custom_components/mail_and_packages/translations/pt_BR.json, custom_components/mail_and_packages/translations/ru.json, custom_components/mail_and_packages/translations/sl.json, custom_components/mail_and_packages/translations/sv.json, custom_components/mail_and_packages/translations/zh_Hant_HK.json
* Google translated config flow strings
* Updated URL in translations
- This PR fixes or closes issue: fixes #145 
=> Updated translations

README.md
The HACS documentation link was recently changed.
- This PR fixes or closes issue: fixes #147 
- This PR is related to issue: #147
=> Updated link to HACS docs

custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/sensor.py
* Added support for Amazon India in const.py
* Previous code was unintentionally parsing all Amazon emails, instead of shipping confirmation mails. Implemented proposal in this comment: https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/issues/125#issuecomment-643792745
* International Amazon emails (UK/IN) have subject length == 10, not 6
- This PR fixes or closes issue: fixes #125 
- This PR is related to issue: #125
=> Amazon International bug fixes

custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/manifest.json, custom_components/mail_and_packages/sensor.py, custom_components/mail_and_packages/translations/ca.json, custom_components/mail_and_packages/translations/de.json, custom_components/mail_and_packages/translations/es.json, custom_components/mail_and_packages/translations/es_419.json, custom_components/mail_and_packages/translations/fi.json, custom_components/mail_and_packages/translations/fr.json, custom_components/mail_and_packages/translations/hu.json, custom_components/mail_and_packages/translations/it.json, custom_components/mail_and_packages/translations/ko.json, custom_components/mail_and_packages/translations/nl.json, custom_components/mail_and_packages/translations/no.json, custom_components/mail_and_packages/translations/pl.json, custom_components/mail_and_packages/translations/pt.json, custom_components/mail_and_packages/translations/pt_BR.json, custom_components/mail_and_packages/translations/ru.json, custom_components/mail_and_packages/translations/sl.json, custom_components/mail_and_packages/translations/sv.json, custom_components/mail_and_packages/translations/zh_Hant_HK.json, requirements.txt
* Add python-resize-image requirement
* New image resize function
* Translation URLs fixed
- This PR fixes or closes issue: fixes #32 fixes #45
=> Resize image

.github/release-drafter.yml, .github/stale.yml, custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/sensor.py
* Filter duplicate notification emails via tracking numbers
- This PR fixes or closes issue: fixes #92
=> Attempt to guard against duplicate emails

custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/sensor.py
Don't len() the int
- This PR fixes or closes issue: fixes #92
=> Don't len() the int

custom_components/mail_and_packages/sensor.py
Initialize list not int
- This PR fixes or closes issue: fixes #207
=> 0.2.2-b24-hotfix

custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/sensor.py
* Handle Amazon Hub emails
* Parse combo from subject line and populate as sensor attribute
- This PR fixes or closes issue: fixes #206
=> Amazon Hub Support

custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/sensor.py
* Swapped DHL search subjects to correct sensors
- This PR fixes or closes issue: fixes #164
=> DHL Subjects were swapped

.github/workflows/codeql-analysis.yml, .github/workflows/pytest.yaml, custom_components/mail_and_packages/helpers.py, tests/conftest.py, tests/test_helpers.py
Added mock_download_img fixture
Change QL time, add python 3.9 checks
=> Fix amazon delivery email test

tests/const.py, tests/test_helpers.py, tests/test_sensor.py
* Fix random image test
* Fix CONFIG_DATA amazon_fwds to a list
=> More test fixes

custom_components/mail_and_packages/__init__.py, custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/helpers.py, custom_components/mail_and_packages/sensor.py, tests/conftest.py, tests/test_helpers.py
* Fixed Datacoordinator not updating states/attributes
* Adjusted tests
=> Fix datacoordinator not updating state/attributes

custom_components/mail_and_packages/__init__.py, custom_components/mail_and_packages/sensor.py, tests/test_helpers.py
* Switch from reload to remove and re-add.
* Remove unused variable
=> Change entity reload

custom_components/mail_and_packages/const.py, requirements_test.txt
* Add additional email address for USPS
- This PR is related to issue: #244
=> Add additional email address for USPS

custom_components/mail_and_packages/const.py
Simple update to fix informed delivery email address.  This likely is a universal change, but I'll tweak this to allow both addresses for now in case i'm wrong.
- This PR fixes or closes issue: fixes #244 
=> Update USPS Informed Delivery email address

.gitignore, custom_components/mail_and_packages/const.py
* Update USPS Informed Delivery from address
- This PR is related to issue: #244
=> Update USPS Informed Delivery from address

.github/workflows/pytest.yaml, custom_components/mail_and_packages/helpers.py
Guard against sensors not loaded in correct order
=> Guard against sensors not loaded in correct order

custom_components/mail_and_packages/helpers.py
Add additional informative debugging messages
=> Add more debuging messages with more information

custom_components/mail_and_packages/const.py, tests/test_emails/informed_delivery.eml, tests/test_emails/informed_delivery_missing_mailpiece.eml, tests/test_emails/informed_delivery_no_mail.eml
* USPS Changes to subject line
* Update tests for USPS
=> USPS Changes to subject line

custom_components/mail_and_packages/helpers.py
Simplify tracking number regex
=> Simplify tracking number regex

custom_components/mail_and_packages/const.py
More USPS changes, subject updated to `Your Daily Digest for Sat, Nov 21`
- This PR fixes or closes issue: fixes #254
=> More USPS Changes

custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/helpers.py, tests/conftest.py, tests/const.py, tests/test_emails/hermes_delivered.eml, tests/test_emails/hermes_out_for_delivery.eml, tests/test_helpers.py
Adds Hermes (UK) Support
- This PR is related to issue: #264
=> Addition of Hermes (UK) support

README.md
=> Change HACS badge

README.md
Mail and Packages is now in the default listing for HACS
=> Update HACS Badge

custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/helpers.py, tests/conftest.py, tests/const.py, tests/test_emails/amazon_uk_delivered.eml, tests/test_emails/amazon_uk_out_for_delivery.eml, tests/test_emails/royal_mail_uk_delivered.eml, tests/test_emails/royal_mail_uk_out_for_delivery.eml, tests/test_helpers.py
* Add Royal Mail UK support
* Add tests for Royal Mail
- This PR fixes or closes issue: fixes #269 
- This PR is related to issue: #262
=> Add Royal Mail UK support

.github/workflows/relase-drafter.yaml
- Fix missing github_token for release drafter
=> Fix missing github_token for release drafter

custom_components/mail_and_packages/const.py, tests/test_helpers.py
=> Add amazon.de

.github/workflows/formatting.yml
=> Formatting update

custom_components/mail_and_packages/helpers.py
- Fix image path for overlays
- Fix typo in Amazon sensor
=> Fix image path and typo

AUTHORS, CONTRIBUTING.md, LICENSE
=> Create contributing guidelines and license

custom_components/mail_and_packages/config_flow.py, custom_components/mail_and_packages/const.py
- Fix missing sensor list in config flow
=> Fix missing sensor list in config flow

custom_components/mail_and_packages/const.py
- Update fedex tracking pattern
=> Update fedex tracking pattern

custom_components/mail_and_packages/__init__.py, custom_components/mail_and_packages/const.py
Increase timeout to 30 seconds for data update coordinator.
- This PR fixes or closes issue: fixes #278
=> Increase timeout to 30 seconds

custom_components/mail_and_packages/__init__.py, custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/helpers.py
Make get_count more manageable
=> Make get_count more manageable

custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/helpers.py
Handle email address list of 1 better
- This PR fixes or closes issue: fixes #298
=> Handle email address list of 1 better

custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/helpers.py, custom_components/mail_and_packages/sensor.py
- Make tracking number attribute manageable
- Remove unused consts, move overlay list to const
=> Make tracking number attribute manageable

custom_components/mail_and_packages/helpers.py, tests/test_helpers.py
* Add missing 'ignore' to a decode
* Add/update tests
=> Add missing ignore to a decode

tests/conftest.py, tests/test_helpers.py
Add test for copyfile exception in get_mails
=> Add test for copyfile exception in get_mails

tests/const.py, tests/test_helpers.py
=> Fixed another test

custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/helpers.py, tests/conftest.py, tests/test_emails/amazon_uk_shipped.eml, tests/test_helpers.py
* Add test email for Amazon UK
* Add Amazon UK patterns
- This PR fixes or closes issue: fixes #262
=> Adjustments for Amazon UK

custom_components/mail_and_packages/const.py
Fix USPS informed delivery email list
=> Fix USPS informed delivery email list

custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/helpers.py
Adjust get_mail for new const structure
=> Adjust get_mail for new const structure

.github/release-drafter.yml, .github/workflows/release.yaml, custom_components/mail_and_packages/helpers.py, tests/conftest.py, tests/test_helpers.py
* Changed some guards for better testing
* Removed unneeded try/excepts
=> More tests

custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/helpers.py, tests/conftest.py, tests/test_emails/amazon_delivered_it.eml, tests/test_emails/amazon_shipped_it.eml, tests/test_helpers.py
* Rework email_search for better usability
* Rework amazon_search
* Rework get_items for better utf-8 support and international support
* Add tests for Amazon.it
- This PR fixes or closes issue: fixes #310
=> Add Amazon.it

.github/release-drafter.yml
=> Better release drafter format

custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/helpers.py
* Added "since" option to email_search for Amazon searches
* Adjust logic on get_tracking
=> Adjust search term for Amazon email search

custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/helpers.py
* Change from SENTON to SINCE imap command
* Fixes #315
- This PR fixes or closes issue: fixes #315
=> Change from SENTON to SINCE imap command 

custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/helpers.py
=> Fix weird merge issue with b19

custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/helpers.py, tests/test_helpers.py
* Guard against decoding issues for amazon emails
* Update test to make sure the email addresses from the list show up in the debug message
=> Guard against decoding issues for amazon emails

custom_components/mail_and_packages/__init__.py, custom_components/mail_and_packages/config_flow.py, custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/helpers.py, tests/const.py, tests/test_config_flow.py, tests/test_helpers.py
* Force Amazon Fwds emails into list format
* Add configuration migration function
* Add tests for Amazon fwds email lists
=> Atempt to fix the amazon fwds

custom_components/mail_and_packages/const.py
* Have UPS delivered emails search for tracking numbers
- This PR fixes or closes issue: fixes #320
=> Adjust UPS delivered to check for tracking numbers

custom_components/mail_and_packages/config_flow.py, custom_components/mail_and_packages/const.py
* Added default value for mp4 toggle to False
=> Fix "user input malformed" error in config_flow

custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/helpers.py
* Rearrange guard logic on amazon fwds check
=> Adjust guard logic on amazon fwds

custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/helpers.py
* Changed the pattern to `findall` instead of `search`
- This PR fixes or closes issue: fixes #320
=> Change search to findall in find_text

custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/helpers.py, tests/conftest.py
* Changed body to body[0] for find_text
* Fixed variable names in tests for consistency
- This PR fixes or closes issue: fixes #320
=> Fix sending wrong search to find_text

custom_components/mail_and_packages/const.py
=> Version bump

custom_components/mail_and_packages/const.py
Adjust FedEx tracking regex
- This PR fixes or closes issue: fixes #334
=> Adjust FedEx tracking regex

README.md
=> Badge update

custom_components/mail_and_packages/__init__.py, custom_components/mail_and_packages/config_flow.py, custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/strings.json, custom_components/mail_and_packages/translations/en.json, tests/const.py, tests/test_config_flow.py
* Allow timeout to be configurable
* Update tests for new feature
- This PR fixes or closes issue: fixes #328
=> Allow timeout to be configurable

custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/helpers.py
Fix count counter in find_text
- This PR fixes or closes issue: fixes #339
=> Fix count counter in find_text

custom_components/mail_and_packages/__init__.py, custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/sensor.py
- Fixed config migration for version 1
- Adjusted path to remove double //
- Fix coordinator data update
- This PR is related to issue: https://community.home-assistant.io/t/mail-and-packages-custom-component-for-ups-fedex-and-usps/118081/1193
=> Fix coordinator data update

custom_components/mail_and_packages/const.py
* Fix wrong Royal mail address
* Add additional subject search for Royal mail
=> Fix wrong Royal mail address

custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/helpers.py, tests/conftest.py, tests/test_helpers.py
Only change the filename daily, this should reduce the amount of problems resulting from the filename changing each time the email is checked.
- This PR is related to issue: #321
=> Only change filename daily

custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/helpers.py, tests/test_helpers.py
Fix path error from #350 
- This PR fixes or closes issue: fixes #351
=> Fix path errors from #350

custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/helpers.py
Handle no gif files found related to #350 and #352
- This PR is related to issue: #321
=> Handle no gif files found

custom_components/mail_and_packages/config_flow.py, custom_components/mail_and_packages/helpers.py, custom_components/mail_and_packages/sensor.py
=> Add typing

tests/conftest.py, tests/test_helpers.py
Finish tests for new function image_file_name
=> Finish tests for new function image_file_name

.github/workflows/release.yaml, custom_components/mail_and_packages/manifest.json, hacs.json
* Add version to manifest.json (new HA requirement)
* Add zip file download to HACS
=> Adjust release workflows

custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/manifest.json, hacs.json
Version in const and manifest are now generated/updated by the release workflow
=> Remove versions from consts

custom_components/mail_and_packages/sensor.py
Remove left over variable.
- This PR fixes or closes issue: fixes #362
=> Remove left over variable

custom_components/mail_and_packages/helpers.py, custom_components/mail_and_packages/manifest.json
Create missing directories as needed
- This PR is related to issue: https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/issues/362#issuecomment-776315208
=> Create missing directories as needed

custom_components/mail_and_packages/__init__.py
Fix ValueError on reload
- This PR is related to issue: #321
=> Fix ValueError on reload

tests/test_config_flow.py
=> Update config_flow tests

custom_components/mail_and_packages/const.py, tests/conftest.py, tests/test_emails/usps_exception.eml, tests/test_helpers.py
Adds USPS Exception sensor
Added tests with sample email
- This PR fixes or closes issue: fixes #369
=> Add USPS Exception sensor

.github/workflows/release-drafter.yaml
Github workflow update for release drafter.
=> Update release drafter to check master and dev

custom_components/mail_and_packages/helpers.py, tests/conftest.py, tests/test_emails/amazon_shipped_alt_timeformat.eml, tests/test_helpers.py
Handle additional date formats in Amazon emails
- This PR fixes or closes issue: fixes #390
=> Handle additional date formats in Amazon emails

custom_components/mail_and_packages/__init__.py, custom_components/mail_and_packages/helpers.py, custom_components/mail_and_packages/sensor.py, tests/test_helpers.py
* Rework DataUpdateCoordinator
* Additional typing
=> Rework DataUpdateCoordinator

custom_components/mail_and_packages/helpers.py, tests/test_camera.py
Additional unit tests
Updated docstrings
Removed unneeded logic from image_file_name
=> More tests/cleanup

.github/ISSUE_TEMPLATE/config.yml, custom_components/mail_and_packages/helpers.py, tests/test_helpers.py
When no errors occur and no files are found return random filename
Revised tests to check for wrong filename output
- This PR fixes or closes issue: fixes #413
=> fix: wrong filename generated

custom_components/mail_and_packages/const.py
Add additional subject for FedEx delivering emails (out for delivery)
=> Add additional subject for FedEx

custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/helpers.py, custom_components/mail_and_packages/sensor.py, tests/conftest.py, tests/const.py, tests/test_emails/amazon_exception.eml, tests/test_helpers.py, tests/test_init.py
Add amazon exception sensor
- This PR is related to issue: #369
=> Add amazon exception sensor

custom_components/mail_and_packages/helpers.py
Fix Amazon exception email address
=> fix: Fix Amazon exception email address

custom_components/mail_and_packages/const.py
Update for new UPS formatted emails
- This PR is related to issue: https://community.home-assistant.io/t/mail-and-packages-custom-component-for-ups-fedex-and-usps/118081/1400
=> fix(shipper): update for new UPS formatted emails

.github/workflows/stale.yml
=> Adjust stale action

custom_components/mail_and_packages/const.py
Add UPS exception sensor
- This PR is related to issue: #369
=> feat: add UPS exception sensor

.github/labeler.yml, .github/workflows/labeler.yml
=> chore: new labeler github action

.github/labeler.yml, .github/release-drafter.yml
=> chore: adjust release-drafter

custom_components/mail_and_packages/helpers.py, tests/test_helpers.py
Resolves a bug in amazon exception sensor.
- This PR fixes or closes issue: fixes #431
=> fix: resolve bug in amazon exception sensor

custom_components/mail_and_packages/helpers.py, tests/test_helpers.py
Filter empty list for amazon forwards
=> fix: filter empty list for amazon forwards

.github/labeler.yml, .github/release-drafter.yml
=> chore: update workflow configs

custom_components/mail_and_packages/const.py
Fix shipper sensor for UPS Delivering sensor, they've changed the email format.
=> fix(shipper): fix usp_delivering sensor

custom_components/mail_and_packages/manifest.json
Add IoT class to manifest.json
=> chore: add IoT class to manifest.json

.github/release-drafter.yml, .github/workflows/labeler.yml, .github/workflows/pr-linter.yml, .github/workflows/release-drafter.yaml
* Disable labeler
* Use release-drafter auto labeler
* Add PR Linter for semantic pr titles
=> chore: workflow changes

custom_components/mail_and_packages/camera.py, custom_components/mail_and_packages/helpers.py, tests/test_camera.py
* Add available property to camera entities
=> fix: add available property to camera entities

.github/release-drafter.yml
* chore: adjust release-drafter config
=> chore: adjust release-drafter config

custom_components/mail_and_packages/camera.py, custom_components/mail_and_packages/config_flow.py, custom_components/mail_and_packages/helpers.py, custom_components/mail_and_packages/strings.json, custom_components/mail_and_packages/translations/en.json, tests/test_camera.py
* fix: config flow not loading new config
* fix: adjust file path generation for new option
- This PR is related to issue: #416
=> fix: custom no mail image config not loading and not displaying

custom_components/mail_and_packages/helpers.py, tests/test_camera.py, tests/test_helpers.py
* Add more debugging
* Minor refactor on "no mail" image
* Add more checks to tests
- This PR is related to issue: #416
=> fix: adjust image_file_name function

custom_components/mail_and_packages/helpers.py
* fix nomail image in get_mails function
- This PR is related to issue: #416
=> fix: fix nomail image in get_mails function

custom_components/mail_and_packages/helpers.py, requirements_test.txt, tests/conftest.py, tests/test_helpers.py
* More error handling
* More debug messages
* Update test requirements
=> feat: more error handling

custom_components/mail_and_packages/const.py
Add additional subject line for USPS delivering sensor
- This PR fixes or closes issue: fixes #473
=> fix: update USPS delivering subject

custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/helpers.py
Parse international dates for Amazon emails
- This PR fixes or closes issue: fixes #478
=> fix: attempt to parse international dates

custom_components/mail_and_packages/const.py
=> fix: add additional language flag

custom_components/mail_and_packages/config_flow.py, custom_components/mail_and_packages/strings.json, custom_components/mail_and_packages/translations/en.json, tests/test_config_flow.py
Add error messages in config flow for interval settings being too low.
- This PR fixes or closes issue: fixes #483
=> fix: better errors for intervals too low

custom_components/mail_and_packages/const.py, tests/test_helpers.py
Update USPS tracking number regex
=> fix(shipper): update USPS tracking number regex

custom_components/mail_and_packages/helpers.py
Fixed tracking number search with multiple subjects.
=> fix: tracking number with multiple subjects search

custom_components/mail_and_packages/helpers.py
=> fix: better fix for #488

custom_components/mail_and_packages/config_flow.py
Fix the user input malformed bug in config flow
=> fix: user input malformed bug in config flow

custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/helpers.py, tests/conftest.py, tests/test_emails/ups_out_for_delivery_new.eml, tests/test_helpers.py
Properly handle HTML email contents
=> fix: properly handle HTML emails

custom_components/mail_and_packages/helpers.py, tests/test_helpers.py
Adjust local warnings to info and adjust amazon count
- This PR fixes or closes issue: 
fixes #504
fixes #502
=> fix: adjust locale warnings to info and adjust amazon count

custom_components/mail_and_packages/camera.py
Don't attempt to update cameras if the data is missing.
- This PR is related to issue: https://community.home-assistant.io/t/mail-and-packages-custom-component-for-ups-fedex-and-usps/118081/1501
=> fix: don't try to update camera if data is missing

README.md, custom_components/mail_and_packages/helpers.py, custom_components/mail_and_packages/sensor.py, tests/test_helpers.py
This will not work in older versions of Home Assistant < 2021.8.x
Swap `state` for `native_value` for Home Assistant code changes
=> refactor: swap state for native_value

custom_components/mail_and_packages/camera.py, custom_components/mail_and_packages/helpers.py
Add height/width to camera entities.
- This PR fixes or closes issue: fixes #511
=> fix: requesting camera height and width

.github/release-drafter.yml, custom_components/mail_and_packages/helpers.py
Change find_text function to work like get_tracking function
- This PR is related to issue: #515
=> fix: adjust find_text function

custom_components/mail_and_packages/helpers.py
Pass the search list directly to find_text.
- This PR is related to issue: #515
=> fix: pass the list directly to find_text

custom_components/mail_and_packages/camera.py, custom_components/mail_and_packages/sensor.py
Group sensors under device entities per mail server that is configured.
=> feat: add sensors into devices

custom_components/mail_and_packages/sensor.py
The unique_id on the sensors was set incorrectly.
=> fix: sensors unique_id wrong

.github/workflows/pytest.yaml, custom_components/mail_and_packages/camera.py, custom_components/mail_and_packages/helpers.py
Add guard against coordinator update failure for cameras.
- This PR is related to issue: #573
=> fix: guard against coordinator update failure in cameras

.github/release-drafter.yml
Update release drafter configuration
=> chore: adjust release drafter config

custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/helpers.py, tests/conftest.py, tests/test_emails/amazon_hub_notice_2.eml, tests/test_helpers.py
Add support for new Amazon Hub email format
- This PR fixes or closes issue: fixes #580
=> fix: add support for new Amazon Hub email format

custom_components/mail_and_packages/const.py, tests/conftest.py, tests/test_emails/fedex_out_for_delivery_2.eml, tests/test_helpers.py
Update FedEx subject search
- This PR fixes or closes issue: fixes #587
=> fix: update fedex subject search

custom_components/mail_and_packages/const.py
Add updated FedEx delivered subject
- This PR is related to issue: #587
=> fix: add fedex delivered subject

custom_components/mail_and_packages/const.py
Update subject for UPS delivering emails
- This PR is related to issue: #592
=> fix: update UPS delivering subject

custom_components/mail_and_packages/helpers.py
Adjust const import in helpers.py
=> refactor: adjust const import

CONTRIBUTING.md, custom_components/mail_and_packages/helpers.py, custom_components/mail_and_packages/strings.json, custom_components/mail_and_packages/translations/en.json, tests/conftest.py, tests/const.py, tests/test_helpers.py, tests/test_sensor.py
Make mail_updated a timestamp device class
- This PR fixes or closes issue: fixes #613
=> feat: make mail_updated a timestamp class

custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/helpers.py, tests/test_helpers.py
Make Amazon easier to manage (thanks @kubawolanin).
Adjusted amazon functions to remove duplicate emails from the fowards list.
This should help with PR #620 
=> refactor: make amazon easier to manage

custom_components/mail_and_packages/helpers.py
Remove utf-8 encoding on default imap search call.
- This PR fixes or closes issue: fixes #628
=> fix: remove utf-8 encoding on default imap search

custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/helpers.py, tests/test_helpers.py
Add German language support for Amazon emails
- This PR is related to issue: #633
=> fix(amazon): add german language support

info.md
=> docs: update hacs info.md

custom_components/mail_and_packages/strings.json, custom_components/mail_and_packages/translations/en.json
Fix spelling mistake in UI
- This PR fixes or closes issue: fixes #646
=> fix: spelling mistake in UI

custom_components/mail_and_packages/strings.json, custom_components/mail_and_packages/translations/ca.json, custom_components/mail_and_packages/translations/de.json, custom_components/mail_and_packages/translations/en.json, custom_components/mail_and_packages/translations/es.json, custom_components/mail_and_packages/translations/es_419.json, custom_components/mail_and_packages/translations/fi.json, custom_components/mail_and_packages/translations/fr.json, custom_components/mail_and_packages/translations/hu.json, custom_components/mail_and_packages/translations/it.json, custom_components/mail_and_packages/translations/ko.json, custom_components/mail_and_packages/translations/nl.json, custom_components/mail_and_packages/translations/no.json, custom_components/mail_and_packages/translations/pl.json, custom_components/mail_and_packages/translations/pt.json, custom_components/mail_and_packages/translations/pt_BR.json, custom_components/mail_and_packages/translations/ru.json, custom_components/mail_and_packages/translations/sl.json, custom_components/mail_and_packages/translations/sv.json, custom_components/mail_and_packages/translations/zh_Hant_HK.json
Update translations also fixes hassfest validation.
=> fix: update translations

custom_components/mail_and_packages/helpers.py
Remove quotes from `SINCE` IMAP search filter.
- This PR fixes or closes issue: fixes #661
=> fix: remove quotes from SINCE date

custom_components/mail_and_packages/helpers.py, tests/conftest.py, tests/test_helpers.py
Enable UTF8 IMAP capability prior to doing UTF8 searching.
Test cleanup (duplicate name stuff)
- This PR is related to issue: #670
=> fix: enable UTF8 IMAP capability

custom_components/mail_and_packages/const.py
Add es_ES to Amazon languages
- This PR fixes or closes issue: fixes #698
=> fix: add es_ES to amazon languages

custom_components/mail_and_packages/const.py
Add pt_PT and pt_BR languages for Amazon
- This PR is related to issue: #698
=> fix: add pt_PT and pt_BR languages for amazon

custom_components/mail_and_packages/helpers.py
Find end of amazon date for es/pt langs
- This PR fixes or closes issue: fixes #698
=> fix: find end of amazon date for es/pt langs

custom_components/mail_and_packages/helpers.py
Add more debug messages to amazon process.
- This PR is related to issue: #698
=> feat: add more debug messages to amazon process

custom_components/mail_and_packages/binary_sensor.py, custom_components/mail_and_packages/helpers.py, custom_components/mail_and_packages/manifest.json, custom_components/mail_and_packages/sensor.py, requirements.txt, tests/conftest.py, tests/test_helpers.py
Fix image size error when generating animated gif.
Removes imageio requirement.
=> fix: resolve image size error

custom_components/mail_and_packages/helpers.py
Add "This contains" to amazon time pattern check.
- This PR fixes or closes issue: fixes #722
=> fix: update amazon time pattern check

custom_components/mail_and_packages/translations/de.json
=> fix: correct german translation

custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/helpers.py
Fixes Amazon.de search pattern for identifying Amazon.de emails.
- This PR fixes or closes issue: fixes #751
=> fix: amazon.de search patterns not fully setup

requirements_test.txt, tests/conftest.py, tests/test_binary_sensor.py, tests/test_camera.py, tests/test_config_flow.py, tests/test_diagnostics.py, tests/test_helpers.py, tests/test_init.py, tests/test_sensor.py
=> test: fix tests

custom_components/mail_and_packages/const.py
Adds additional subjects to UPS shipper.
- This PR fixes or closes issue: fixes #765
=> fix(shipper): add additional subjects for UPS shipper

custom_components/mail_and_packages/helpers.py
The `find_text` function was only searching for the first item in the list, added a for loop
to the function to resolve this.
- This PR fixes or closes issue: fixes #775
=> fix: find_text was only searching for the first item in list

.devcontainer/README.md
Minor change to the Step by Step debugging on the dev container folder
This PR adds a small note to the dev container README.md - On multiple machines I have run into Git error 128 when trying to run HA on the initial pull process. Setting Git to use HTTPs over git resolves the issue and allows you to build the container
=> docs: Add git fix

custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/helpers.py, tests/test_helpers.py
Add Amazon.fr to amazon sensor.
- This PR fixes or closes issue: fixes #774
=> feat: add amazon.fr to amazon sensor

custom_components/mail_and_packages/const.py
Co-authored-by: @glbailey
Adds Purolator and Intelcom Canadian Shippers
=> feat(shipper): add Purolator and Intelcom shippers

custom_components/mail_and_packages/camera.py, custom_components/mail_and_packages/helpers.py, custom_components/mail_and_packages/sensor.py
Changes more messages from `warning` to `debug`.
=> fix: change additional messages to debug only

custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/helpers.py
Added new carrier for Atlantic Canada Region - Bonshaw Distribution Network
=> feat(shipper): add new carrier Bonshaw distribution network

custom_components/mail_and_packages/const.py
Add walmart shipper
- This PR is related to issue: #806
=> feat(shipper): add walmart shipper

custom_components/mail_and_packages/sensor.py, tests/test_sensor.py
Keeps tracking numbers with the delivered sensor.
- This PR fixes or closes issue: fixes #762
=> feat: add tracking numbers to delivered sensor

custom_components/mail_and_packages/translations/sk.json
=> build: add slovak translation

custom_components/mail_and_packages/helpers.py, tests/test_helpers.py
fixing utf8 support
- This PR fixes or closes issue: fixes #815
=> fix: utf8 enable

custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/helpers.py
Move amazon date parsing to their own functions
- This PR is related to issue: #751
=> refactor: adjust amazon date functions

custom_components/mail_and_packages/helpers.py, tests/test_helpers.py
Fix gif to mp4 conversion
- This PR fixes or closes issue: fixes #819
=> fix: gif to mp4 conversion

custom_components/mail_and_packages/helpers.py
Fix UTF8 subject searches
- This PR fixes or closes issue: fixes #832
=> fix: fix utf8 searches

custom_components/mail_and_packages/sensor.py
Fix error with sensors when IMAP connection fails.
=> fix: fix error when imap connection fails

custom_components/mail_and_packages/helpers.py
Make sure Amazon subjects are strings
- This PR fixes or closes issue: fixes #853
=> fix: make sure subject is a string

.github/workflows/pytest.yaml, custom_components/mail_and_packages/__init__.py, custom_components/mail_and_packages/binary_sensor.py, custom_components/mail_and_packages/camera.py, custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/diagnostics.py, custom_components/mail_and_packages/helpers.py, custom_components/mail_and_packages/manifest.json, custom_components/mail_and_packages/sensor.py, pylintrc, requirements.txt, requirements_test.txt, setup.cfg, tests/conftest.py, tests/test_binary_sensor.py, tests/test_camera.py, tests/test_diagnostics.py, tests/test_helpers.py, tests/test_init.py, tests/test_sensor.py, tox.ini
Fixes date parsing for amazon sensors.
- This PR fixes or closes issue: fixes #874 #841 #751
=> fix: fix dateparsing for amazon sensors

custom_components/mail_and_packages/__init__.py
Use `hass.config_entries.async_update_entry` to update options entries.
=> refactor: maintenance update for 2024.3.x+

custom_components/mail_and_packages/const.py
Update Amazon locker (formerly hub) email parsing.
- This PR fixes or closes issue: fixes #881
=> fix(shipper): update for amazon locker pickup emails

custom_components/mail_and_packages/__init__.py, custom_components/mail_and_packages/binary_sensor.py, custom_components/mail_and_packages/camera.py, custom_components/mail_and_packages/helpers.py, tests/test_binary_sensor.py, tests/test_helpers.py
Stop blocking calls in the event loop.
- This PR fixes or closes issue: fixes #897
=> fix: stop blocking the event loop

custom_components/mail_and_packages/helpers.py
Fix additional blocking calls.
- This PR fixes or closes issue: fixes #897
=> fix: more blocking fixes

custom_components/mail_and_packages/camera.py
Fixes blocking in camera module
- This PR fixes or closes issue: fixes #897
=> fix: blocking in camera

README.md
Update README, remove invalid badges from README.
=> chore(repo): update README.md

custom_components/mail_and_packages/helpers.py
Fix blocking call in `amazon_search` function.
- This PR fixes or closes issue: fixes #908
=> fix: fix blocking call in `amazon_search` function

custom_components/mail_and_packages/camera.py
Validate keys in coordinator data before attempting to reference them in camera.py
- This PR fixes or closes issue: fixes #907
=> fix: validate keys in coordinator data for camera

custom_components/mail_and_packages/const.py
German post.de email subject update
- This PR fixes or closes issue: fixes #894
=> fix(shipper): german post.de email subject update

custom_components/mail_and_packages/__init__.py
Remove extra if statement block from configuration migration function.
- This PR fixes or closes issue: fixes #917
=> fix: misplaced if statment in config migration

.github/workflows/pytest.yaml, custom_components/mail_and_packages/__init__.py, custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/helpers.py, tests/test_helpers.py
Better fix for IO blocking issue
- This PR is related to issue: #906 #908
=> fix: better fix for io blocking

custom_components/mail_and_packages/const.py, custom_components/mail_and_packages/helpers.py, tests/test_binary_sensor.py, tests/test_helpers.py
Fix IO blocking when downloading Amazon images
- This PR is related to issue: https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/issues/908#issuecomment-2184259537
=> fix: io blocking when downloading amazon images

custom_components/mail_and_packages/const.py, tests/test_helpers.py
Add Amazon.nl support.
- This PR fixes or closes issue: fixes #925
=> feat(shipper): add amazon.nl support

.github/release-drafter.yml
Adjust release drafter configuration
=> chore: update release drafter config

custom_components/mail_and_packages/const.py
Finish amazon.nl support
- This PR fixes or closes issue: fixes #925
=> fix(shipper): finish amazon.nl support

custom_components/mail_and_packages/__init__.py, custom_components/mail_and_packages/helpers.py
Switch to `async_forward_entry_setups` for setting up integration platforms.
Add try/except to `fetch` function in `process_emails` with error message.
=> fix: use `async_forward_entry_setups` for HA 2024.7.x+

.github/release-drafter.yml, hacs.json
Update repo files hacs.json and release drafter config.
=> chore: update hacs.json and release drafter config

custom_components/mail_and_packages/services.yaml
There was a typo in the service call :)
=> fix: typo in service call

custom_components/mail_and_packages/__init__.py, custom_components/mail_and_packages/config_flow.py, custom_components/mail_and_packages/const.py, tests/conftest.py, tests/test_init.py
Set a default image path.
- This PR fixes or closes issue: fixes #944
=> fix: fix missing config for image path

custom_components/mail_and_packages/diagnostics.py, tests/test_diagnostics.py
Redact amazon forward emails from diagnostics
=> refactor: redact amazon forward emails from diagnostics

custom_components/mail_and_packages/__init__.py, custom_components/mail_and_packages/config_flow.py, custom_components/mail_and_packages/const.py, tests/conftest.py
Workaround for release workflow issue.
- This PR fixes or closes issue: fixes #949
=> fix: workaround for release workflow issue

custom_components/mail_and_packages/helpers.py
Better image path managment.
- This PR fixes or closes issue: fixes #944 
- This PR is related to issue: https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/discussions/947#discussioncomment-10066903
=> fix: better image path replacement

custom_components/mail_and_packages/config_flow.py
Fix missed configuration import for the Amazon reconfigure flow
- This PR is related to issue: #937
=> fix: missing config import for amazon reconfigure flow
